// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slmemkihimqflhkruxqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsbWVta2loaW1xZmxoa3J1eHFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NDk5NDksImV4cCI6MjA2MjEyNTk0OX0.I0papivu4VUessBF7YgURF2Yvx2nKWVkKs2mwmJaZsY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);